/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.weibo.sdk.android;

public   class R {
    public static   class array {
        public static   int api_types=0x7f040000;
        public static   int examples=0x7f040001;
    }
    public static   class attr {
    }
    public static   class color {
        public static   int weibosdk_dialog_title_blue=0x7f050002;
        public static   int weibosdk_text_num_gray=0x7f050001;
        public static   int weibosdk_transparent=0x7f050000;
    }
    public static   class dimen {
        public static   int padding_large=0x7f060002;
        public static   int padding_medium=0x7f060001;
        public static   int padding_small=0x7f060000;
        public static   int weibosdk_dialog_bottom_margin=0x7f060006;
        public static   int weibosdk_dialog_left_margin=0x7f060003;
        public static   int weibosdk_dialog_right_margin=0x7f060005;
        public static   int weibosdk_dialog_top_margin=0x7f060004;
    }
    public static   class drawable {
        public static   int bg_btn=0x7f020000;
        public static   int bg_content=0x7f020001;
        public static   int bg_delwords=0x7f020002;
        public static   int bg_delwords_nor=0x7f020003;
        public static   int bg_delwords_sel=0x7f020004;
        public static   int bg_title=0x7f020005;
        public static   int close_normal=0x7f020006;
        public static   int close_press=0x7f020007;
        public static   int close_selector=0x7f020008;
        public static   int del_pic=0x7f020009;
        public static   int dialog_bg=0x7f02000a;
        public static   int ic_action_search=0x7f02000b;
        public static   int ic_launcher=0x7f02000c;
        public static   int icon=0x7f02000d;
        public static   int icon_delwords=0x7f02000e;
        public static   int image_background=0x7f02000f;
        public static   int title_logo=0x7f020010;
        public static   int weibosdk_bg_btn=0x7f020011;
        public static   int weibosdk_bg_content=0x7f020012;
        public static   int weibosdk_bg_delwords=0x7f020013;
        public static   int weibosdk_bg_delwords_nor=0x7f020014;
        public static   int weibosdk_bg_delwords_sel=0x7f020015;
        public static   int weibosdk_bg_title=0x7f020016;
        public static   int weibosdk_close_normal=0x7f020017;
        public static   int weibosdk_close_press=0x7f020018;
        public static   int weibosdk_close_selector=0x7f020019;
        public static   int weibosdk_del_pic=0x7f02001a;
        public static   int weibosdk_dialog_bg=0x7f02001b;
        public static   int weibosdk_icon_delwords=0x7f02001c;
        public static   int weibosdk_image_background=0x7f02001d;
        public static   int weibosdk_title_logo=0x7f02001e;
    }
    public static   class id {
        public static   int apiCancel=0x7f0a0003;
        public static   int auth=0x7f0a0000;
        public static   int menu_settings=0x7f0a0004;
        public static   int show=0x7f0a0002;
        public static   int sso=0x7f0a0001;
    }
    public static   class layout {
        public static   int activity_main=0x7f030000;
    }
    public static   class menu {
        public static   int activity_main=0x7f090000;
    }
    public static   class string {
        public static   int app_name=0x7f070000;
        public static   int menu_settings=0x7f070001;
        public static   int testcontent=0x7f070013;
        public static   int title_activity_main=0x7f070002;
        public static   int weibosdk_app_name=0x7f070007;
        public static   int weibosdk_attention=0x7f070003;
        public static   int weibosdk_cancel=0x7f070006;
        public static   int weibosdk_close=0x7f07000a;
        public static   int weibosdk_comment=0x7f070010;
        public static   int weibosdk_del_pic=0x7f07000f;
        public static   int weibosdk_delete_all=0x7f070004;
        public static   int weibosdk_fav=0x7f070012;
        public static   int weibosdk_forward=0x7f070011;
        public static   int weibosdk_ok=0x7f070005;
        public static   int weibosdk_photo=0x7f070009;
        public static   int weibosdk_please_login=0x7f07000c;
        public static   int weibosdk_send=0x7f070008;
        public static   int weibosdk_send_failed=0x7f07000e;
        public static   int weibosdk_send_sucess=0x7f07000d;
        public static   int weibosdk_share_dialog_title=0x7f07000b;
    }
    public static   class style {
        public static   int AppTheme=0x7f080000;
    }
}
